name: Pull PR Labels

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pull_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR Labels
        id: get_labels
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/labels)
          if [[ $? -ne 0 ]]; then
            echo "Failed to fetch labels."
            exit 1
          fi
          echo "Response from API: $response"
          labels=$(echo "$response" | jq -r '.[].name')
          if [[ $? -ne 0 ]]; then
            echo "Failed to parse labels."
            echo "Response: $response"
            exit 1
          fi
          echo "Fetched labels: $labels"
          echo "::set-output name=labels::$labels"
