name: List Closed Pull Requests

on:
  workflow_dispatch:

jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
      - name: List closed pull requests
        uses: actions/github-script@v5
        with:
          script: |
            const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');
            const { data: pulls } = await octokit.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });
            console.log(pulls.map(pull => `${pull.html_url} - ${pull.title}`).join('\n'));
