on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  check_pull_requests:
    runs-on: self-hosted  # Specify that the job should run on a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Pull Docker image
        run: docker pull python:3.x

      - name: Run Python script in Docker
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace python:3.x python GitPull.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
